apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-html-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/shreyas-quizizz/sampleApp.git
    targetRevision: HEAD
    path: .
    directory:
      exclude: '*.json,*.js,*.html,*.sh,*.md'
      include: '*.yaml,*.yml'
  destination:
    server: https://kubernetes.default.svc
    namespace: default 