apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins-bot
  namespace: argocd
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: jenkins-bot-role
  namespace: argocd
rules:
  - apiGroups: ["argoproj.io"]
    resources: ["applications"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-bot-binding
  namespace: argocd
subjects:
  - kind: ServiceAccount
    name: jenkins-bot
    namespace: argocd
roleRef:
  kind: Role
  name: jenkins-bot-role
  apiGroup: rbac.authorization.k8s.io 