apiVersion: v1
kind: ServiceAccount
metadata:
  name: argocd-api-access
  namespace: argocd
---
apiVersion: v1
kind: Secret
metadata:
  name: argocd-api-access-token
  namespace: argocd
  annotations:
    kubernetes.io/service-account.name: argocd-api-access
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argocd-api-access-role
rules:
- apiGroups: ["argoproj.io"]
  resources: ["applications", "applicationsets", "appprojects"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["secrets", "configmaps"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argocd-api-access-binding
subjects:
- kind: ServiceAccount
  name: argocd-api-access
  namespace: argocd
roleRef:
  kind: ClusterRole
  name: argocd-api-access-role
  apiGroup: rbac.authorization.k8s.io 